### ISSUE TITLE
objectIsMusicTrack check for valid music file is malformed against obj.Kind 

### ISSUE THREAD

**Issue by edickins** [johnpaulvaughan/itunes-music-library-tracks#1]
Hi

The current code for objectIsMusicTrack has a malformed test for the obj.Kind

obviously this is six years old so it is fair that it is not up to date with the 'Apple Music AAC audio file' type, but the test on obj.Kind is malformed. It should look like this with the test on the String in obj.Kind being re-tested explicitly against the value, rather than as a series of '||' separators.

function objectIsMusicTrack(obj) {
if ((obj.Name || obj.Artist)
&& !obj['Playlist ID']
&& ((obj.Kind =='MPEG audio file')
|| (obj.Kind =='AAC audio file')
|| (obj.Kind =='Matched AAC audio file')
|| (obj.Kind =='Protected AAC audio file')
|| (obj.Kind =='Purchased AAC audio file')
|| (obj.Kind =='Apple Music AAC audio file')))
return true;
else
return false;
}

**Comment by johnpaulvaughan** [comment]
Thanks @edickins for highlighting the problem and creating a PR to fix it :-) I must have been drunk when I initially wrote that function!

**Comment by edickins** [comment]
no problem I am pleased it was a good fix.  I reinstalled the package from npmjs.com but it doesn't show the updated code that's in the GitHub repo. Does it need to be published by you or should I use the version from GitHub?  I am not deploying yet so everything is local but I'll be wanting to deploy on my server eventually.  cheers.

**Comment by johnpaulvaughan** [comment]
Hi @edickins , I've just pushed the repository to npm. I used a VSCode tool which automatically bumped the version to 1.2.0, but nothing has technically changed other than the patches you applied. 

I don't actually have iTunes anymore to ensure any changes that you made are working, so I've added you as a contributor in github to make it a bit more streamlined for you to work with it. If you create an NPM account I'll also add you as a contributor there, so that you can publish any changes you make without waiting for me. 

Good luck with your project.

**Comment by edickins** [comment]
fantastic, thanks.  I will take a look.  so I create an NPM account for publishing and it will publish in to the existing NPM Module?  very exciting.

**Comment by edickins** [comment]
Hi @johnpaulvaughan my npmjs.com profile is this https://www.npmjs.com/~bleep
